server:
  port: 80

cors:
  originPatterns: http://localhost:8080,http://localhost:3000

spring:
  application:
    name: AlpacaFilmes
  profiles:
    active: dev
  jpa:
    open-in-view: false

the-movie-db:
  token: ${the_movie_db}
